### ISSUE TITLE
Update daemon dependency to v2.0.6

### ISSUE THREAD

**Issue by alambike** [vrdominguez/ddns-daemon#4]
The daemon doesn't work with latest python-daemon (2.0.6) version, needs 1.5.5 version installed

**Comment by vrdominguez** [comment]
In which "distro" did you try the daemon?

If ubuntu 14.04 LTS, the problem is the system package for python-lockfile, needed by deja-dup (system backups)

```
vrdominguez@skaro:~$ aptitude show python-lockfile | fgrep 'Versi'                    
Versión: 1:0.8-2ubuntu2
```

The oficial package for ubuntu is version 0.8.

In order to make python-daemon 2.0.X work, you need an updated version (current is 0.10.2):

```
vrdominguez@skaro:~$ pip search lockfile
lockfile                  - Platform-independent file locking module
  INSTALLED: 0.8
  LATEST:    0.10.2
```

**Comment by alambike** [comment]
Ok, it works but I have to uninstall python-lockfile system package, and with it:
  deja-dup deja-dup-backend-gvfs duplicity python-lockfile

and if I install deja-dup again, apt insist to install python-lockfile, what returns to break ddnsDaemon

**Comment by vrdominguez** [comment]
For ubuntu, the best solution is using the oficial package for python-daemon, to avoid problems with versions:

```
vrdominguez@skaro:~$ aptitude show python-daemon | fgrep Versi
Versión: 1.5.5-1ubuntu1
```

With this package installed, you get a working 1.5.5 python-daemon library:

```
vrdominguez@skaro:~$ pip search python-daemon | fgrep -A2 python-daemon
python-daemon             - Library to implement a well-behaved Unix daemon process.
  INSTALLED: 1.5.5
  LATEST:    2.0.6
```

**Comment by alambike** [comment]
Right! It works perfectly now, maybe could be listed as dependencies.
Thanks

**Comment by alambike** [comment]
Fixed for me, closing issue.
